#include "nsISupports.idl"
#include "nsIArray.idl"

[scriptable, function, uuid(4ab3e1df-2c04-43d2-9c71-2ccf9e531898)]
interface nsIIdentityManagerLoginButtonCallback {
};

[scriptable, uuid(ec8030f7-c20a-464f-9b0e-13a3a9e97384)]
interface nsIIdentityManager : nsISupports {
  void createSignInButton(in nsIArray providers, in nsIArray attributes, 
                          in AString domID,
                          in nsIIdentityManagerLoginButtonCallback callback);
};
